name: Generate Teams

on:
  workflow_dispatch:

jobs:
  create-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: |
          pip install requests

      - name: GENERATE THE TEAMS
        run: |
          python teammaker.py
